const ListOfOrchids = [
  {
    Id: 1,
    name: "Taichung beauty",
    rating: 5,
    isSpecial: true,
    image: "src/assets/flower/hoa1.jpg",
    color: "pink",
    origin: "Taiwan",
    category: "Cattleya",
  },
  {
    Id: 2,
    name: "Tokyo Charm",
    rating: 4,
    isSpecial: false,
    image: "src/assets/flower/hoa2.jpg",
    color: "white",
    origin: "Japan",
    category: "Phalaenopsis",
  },
  {
    Id: 3,
    name: "Bangkok Delight",
    rating: 5,
    isSpecial: true,
    image: "src/assets/flower/hoa3.jpg",
    color: "yellow",
    origin: "Thailand",
    categor: "Dendrobium",
  },
  {
    Id: 4,
    name: "Manila Grace",
    rating: 4,
    isSpecial: false,
    image: "src/assets/flower/hoa4.jpg",
    color: "purple",
    origin: "Philippines",
    category: "Vanda",
  },
  {
    Id: 5,
    name: "Hanoi Elegance",
    rating: 5,
    isSpecial: true,
    image: "src/assets/flower/hoa5.jpg",
    color: "red",
    origin: "Vietnam",
    category: "Paphiopedilum",
  },
  {
    Id: 6,
    name: "Jakarta Jewel",
    rating: 4,
    isSpecial: false,
    image: "src/assets/flower/hoa6.jpg",
    color: "red",
    origin: "Vietnam",
    category: "Paphiopedilum",
  },
  {
    Id: 7,
    name: "Mumbai Majesty",
    rating: 5,
    isSpecial: true,
    image: "src/assets/flower/hoa7.jpg",
    color: "purple",
    origin: "India",
    category: "Cattleya",
  },
  {
    Id: 8,
    name: "Delhi Delight",
    rating: 4,
    isSpecial: false,
    image: "src/assets/flower/hoa8.jpg",
    color: "yellow",
    origin: "India",
    category: "Dendrobium",
  },
  {
    Id: 9,
    name: "Cairo Charm",
    rating: 5,
    isSpecial: true,
    image: "src/assets/flower/hoa9.jpg",
    color: "white",
    origin: "Egypt",
    category: "Phalaenopsis",
  },
  {
    Id: 10,
    name: "Nairobi Nectar",
    rating: 4,
    isSpecial: false,
    image: "src/assets/flower/hoa10.jpg",
    color: "red",
    origin: "Kenya",
    category: "Paphiopedilum",
  },
  {
    Id: 11,
    name: "Cape Town Cascade",
    rating: 5,
    isSpecial: true,
    image: "src/assets/flower/hoa11.jpg",
    color: "blue",
    origin: "South Africa",
    category: "Oncidium",
  },
  {
    Id: 12,
    name: "Sydney Star",
    rating: 4,
    isSpecial: false,
    image: "src/assets/flower/hoa12.jpg",
    color: "orange",
    origin: "Australia",
    category: "Cymbidium",
  },
  {
    Id: 13,
    name: "Auckland Aura",
    rating: 5,
    isSpecial: true,
    image: "src/assets/flower/hoa13.jpg",
    color: "green",
    origin: "New Zealand",
    category: "Bulbophyllum",
  },
  {
    Id: 14,
    name: "Buenos Aires Beauty",
    rating: 4,
    isSpecial: false,
    image: "src/assets/flower/hoa14.jpg",
    color: "purple",
    origin: "Argentina",
    category: "Brassavola",
  },
  {
    Id: 15,
    name: "Rio Radiance",
    rating: 5,
    isSpecial: true,
    image: "src/assets/flower/hoa15.jpg",
    color: "yellow",
    origin: "Brazil",
    category: "Coelogyne",
  },
  {
    Id: 16,
    name: "Santiago Splendor",
    rating: 4,
    isSpecial: false,
    image: "src/assets/flower/hoa16.jpg",
    color: "red",
    origin: "Chile",
    category: "Epidendrum",
  },
];
export default ListOfOrchids;
